<Project Sdk="Microsoft.NET.Sdk">

	<Import Project="..\tModLoader.targets" />

	<PropertyGroup>
		<Nullable>enable</Nullable>
	</PropertyGroup>

	<ItemGroup>
		<Reference Include="ShatteredMusiMod">
			<HintPath>lib\ShatteredMusiMod.dll</HintPath>
		</Reference>

		<Reference Include="StructureHelper">
			<HintPath>lib\StructureHelper.dll</HintPath>
		</Reference>
	</ItemGroup>


</Project>